### ISSUE TITLE
publish new version?

### ISSUE THREAD

**Issue by zkat** [yoshuawuyts/mkdirp#3]
**Choose one:** a 🙋 feature request

https://github.com/yoshuawuyts/mkdirp/pull/2 added a new feature, but it hasn't been published to crates.io

## Expected Behavior

`cargo add mkdirp` includes the above patch.

## Current Behavior

It does not include the patch.

## Possible Solution

Publishing a new version yourself, or go through with giving me publish rights on crates.io and I can do it myself! :)

## Context

I need this published so I can publish [cacache](https://github.com/zkat/cacache-rs).

**Comment by yoshuawuyts** [comment]
I thought I added you a couple of days ago! -- Crates.io is different from npm in that invites need to be explicitely accepted, and I don't believe there's email notifications. Go to https://crates.io/me/pending-invites to accept the invite!

**Comment by zkat** [comment]
ah! I didn't get a notification and couldn't find that page. I'm all set now, thank you!
